language: python
python:
    - '2.7'
install: pip install -r requirements.txt
script: make test
notifications:
    email:
        recipients:
            - benjamin@bengfort.com
            - matthew.paisner@gmail.com
            - maynord@umd.edu
            - michaelcox2525@yahoo.com
        on_success: change
        on_failure: always
